"use client";

import { motion } from "framer-motion";
import { Download } from "lucide-react";

const fadeIn = (delay: number) => ({
  initial: { opacity: 0, y: 20 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
  transition: { duration: 0.6, delay },
});

export function CVSection() {
  return (
    <section className="min-h-screen pt-24 pb-16 px-4 md:px-8 lg:px-16">
      <div className="max-w-5xl mx-auto">
        <motion.div {...fadeIn(0)}>
          <h2 className="text-2xl font-normal mb-8 lowercase">curriculum vitae</h2>
        </motion.div>

        <motion.div {...fadeIn(0.1)} className="mb-12">
          <a
            href="/cv.pdf"
            download="Josephine_Baggen_CV.pdf"
            className="inline-flex items-center gap-2 border border-border px-4 py-2 rounded text-sm text-muted-foreground hover:text-foreground hover:border-primary transition-colors"
          >
            <Download className="w-4 h-4" />
            <span>Download CV (PDF)</span>
          </a>
        </motion.div>

        <div className="space-y-14">

          {/* Education */}
          <motion.div {...fadeIn(0.15)}>
            <h3 className="text-lg font-medium text-primary mb-6">Education</h3>
            <div className="space-y-7">
              <div className="flex flex-col md:flex-row md:gap-8">
                <span className="text-sm text-muted-foreground md:min-w-[140px] shrink-0">Expected 2027</span>
                <div>
                  <p className="font-medium">Ph.D. Astronomy</p>
                  <p className="text-muted-foreground text-sm">Yale University, New Haven, CT</p>
                  <p className="text-muted-foreground text-sm mt-1 italic leading-relaxed">
                    Thesis: Connecting the Dots with the James Webb Space Telescope: The Formation of Compact Galaxies and Massive Black Holes in the Early Universe
                  </p>
                  <p className="text-muted-foreground text-sm mt-1">Advisor: Prof.dr. P. van Dokkum</p>
                </div>
              </div>
              <div className="flex flex-col md:flex-row md:gap-8">
                <span className="text-sm text-muted-foreground md:min-w-[140px] shrink-0">2020–2022</span>
                <div>
                  <p className="font-medium">Master Astronomy &amp; Cosmology <span className="font-normal text-muted-foreground text-sm">— Graduated with Honours</span></p>
                  <p className="text-muted-foreground text-sm">Leiden University, The Netherlands</p>
                  <p className="text-muted-foreground text-sm mt-1 italic">Thesis II: The highest redshift radio galaxies</p>
                  <p className="text-muted-foreground text-sm">Advisor: Prof.dr. H.J.A. Röttgering, Dr. A. Gloudemans</p>
                  <p className="text-muted-foreground text-sm mt-1 italic">Thesis I: Transformation of Galaxy Morphology and Alignment in Galaxy Clusters</p>
                  <p className="text-muted-foreground text-sm">Advisor: Prof.dr. H. Hoekstra, Dr. Y.M. Bahé</p>
                </div>
              </div>
              <div className="flex flex-col md:flex-row md:gap-8">
                <span className="text-sm text-muted-foreground md:min-w-[140px] shrink-0">2017–2020</span>
                <div>
                  <p className="font-medium">Bachelor Astronomy</p>
                  <p className="text-muted-foreground text-sm">Leiden University, The Netherlands</p>
                  <p className="text-muted-foreground text-sm mt-1 italic">Thesis: Hyper-velocity Stars generated by the Large Magellanic Cloud</p>
                  <p className="text-muted-foreground text-sm">Advisor: Prof.dr. E.M. Rossi, Dr. F. Evans</p>
                </div>
              </div>
            </div>
          </motion.div>

          {/* Publications */}
          <motion.div {...fadeIn(0.2)}>
            <h3 className="text-lg font-medium text-primary mb-2">Publications</h3>
            <p className="text-sm text-muted-foreground mb-6">
              5 first-author papers · 16 total papers · h-index 10 · ~1000 citations.{" "}
              <a href="https://ui.adsabs.harvard.edu/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">ADS library ↗</a>
            </p>

            <h4 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-4">First Authored</h4>
            <ol className="space-y-4 list-decimal list-outside ml-4 text-sm">
              {[
                { authors: "Baggen, J. F. W., van Dokkum, P., et al.", title: "Connecting the Dots: UV-bright Companions of Little Red Dots as Lyman–Werner Sources Enabling Direct-collapse Black Hole Formation", journal: "ApJL, 1002, L4", year: "2026", doi: "10.3847/2041-8213/ae58a5" },
                { authors: "Baggen, J. F. W., van den Bosch, F., et al.", title: "The Impact of Baryonic Effects on the Dynamical Masses Inferred Using Satellite Kinematics", journal: "The Open Journal of Astrophysics, 9, 58198", year: "2026", doi: "10.33232/001c.158198" },
                { authors: "Baggen, J. F. W., van Dokkum, P., et al.", title: "(Re)solving the complex multi-scale morphology and V-shaped SED of a newly discovered strongly-lensed Little Red Dot in Abell 383", journal: "arXiv e-prints", year: "2025", doi: "10.48550/arXiv.2512.03239" },
                { authors: "Baggen, J. F. W., van Dokkum, P., et al.", title: "The Small Sizes and High Implied Densities of \"Little Red Dots\" with Balmer Breaks Could Explain Their Broad Emission Lines without an Active Galactic Nucleus", journal: "ApJL, 977, L13", year: "2024", doi: "10.3847/2041-8213/ad90b8" },
                { authors: "Baggen, J. F. W., van Dokkum, P., et al.", title: "Sizes and Mass Profiles of Candidate Massive Galaxies Discovered by JWST at 7 < z < 9: Evidence for Very Early Formation of the Central 100 pc of Present-day Ellipticals", journal: "ApJL, 955, L12", year: "2023", doi: "10.3847/2041-8213/acf5ef" },
              ].map((p, i) => (
                <li key={i} className="pl-1">
                  <span className="text-foreground">{p.authors}</span>{" "}
                  <span className="text-muted-foreground">"{p.title}"</span>{" "}
                  <span className="italic text-muted-foreground">{p.journal}</span>{" "}
                  <span className="text-muted-foreground">({p.year}).</span>{" "}
                  <a href={`https://doi.org/${p.doi}`} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">doi:{p.doi}</a>
                </li>
              ))}
            </ol>

            <h4 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-4 mt-8">Contributing Author</h4>
            <ol className="space-y-3 list-decimal list-outside ml-4 text-sm">
              {[
                { authors: "van Dokkum, P., Brammer, G., Jennings, C., Pasha, I., Baggen, J. F. W.", title: "Further Evidence for a Direct-collapse Origin of the Supermassive Black Hole at the Center of the ∞ Galaxy", journal: "ApJL, 990, L48", year: "2025", doi: "10.3847/2041-8213/adfb50" },
                { authors: "van Dokkum, P., Brammer, G., Baggen, J. F. W., et al.", title: "The ∞ Galaxy: A Candidate Direct-collapse Supermassive Black Hole between Two Massive, Ringed Nuclei", journal: "ApJL, 988, L6", year: "2025", doi: "10.3847/2041-8213/addcfe" },
                { authors: "Mitra, K., van den Bosch, F. C., Baggen, J. F. W., Lange, J. U.", title: "BASILISK IV. No S8 Tension with Satellite Kinematics", journal: "arXiv e-prints", year: "2025", doi: "10.48550/arXiv.2512.14889" },
                { authors: "D'Eugenio, F., Nelson, E., Ji, X., Baggen, J. F. W., et al.", title: "Irony at z = 6.68: a bright AGN with forbidden Fe emission and multi-component Balmer absorption", journal: "arXiv e-prints", year: "2025", doi: "10.48550/arXiv.2510.00101" },
                { authors: "Naidu, R. P., Matthee, J., Katz, H., et al. (incl. Baggen, J. F. W.)", title: "A 'Black Hole Star' Reveals the Remarkable Gas-Enshrouded Hearts of the Little Red Dots", journal: "arXiv e-prints", year: "2025", doi: "10.48550/arXiv.2503.16596" },
                { authors: "de Graaff, A., Rix, H.-W., Naidu, R. P., et al. (incl. Baggen, J. F. W.)", title: "A remarkable Ruby: Absorption in dense gas, rather than evolved stars, drives the extreme Balmer break of a Little Red Dot at z = 3.5", journal: "A&A, 701, A168", year: "2025", doi: "10.1051/0004-6361/202554681" },
                { authors: "Barrufet, L., Oesch, P. A., Marques-Chaves, R., Arellano-Cordova, K., Baggen, J. F. W., et al.", title: "Quiescent or dusty? Unveiling the nature of extremely red galaxies at z > 3", journal: "MNRAS", year: "2025", doi: "10.1093/mnras/staf013" },
                { authors: "Weibel, A., de Graaff, A., Setton, D. J., et al. (incl. Baggen, J. F. W.)", title: "RUBIES Reveals a Massive Quiescent Galaxy at z = 7.3", journal: "ApJ, 983, 11", year: "2025", doi: "10.3847/1538-4357/adab7a" },
                { authors: "Wang, B., Leja, J., de Graaff, A., et al. (incl. Baggen, J. F. W.)", title: "RUBIES: Evolved Stellar Populations with Extended Formation Histories at z ∼ 7–8 in Candidate Massive Galaxies Identified with JWST/NIRSpec", journal: "ApJL, 969, L13", year: "2024", doi: "10.3847/2041-8213/ad55f7" },
                { authors: "Evans, F. A., Marchetti, T., Rossi, E. M., Baggen, J. F. W., Bloot, S.", title: "Comparing hypervelocity star populations from the Large Magellanic Cloud and the Milky Way", journal: "MNRAS, 507, 4997", year: "2021", doi: "10.1093/mnras/stab2271" },
              ].map((p, i) => (
                <li key={i} className="pl-1 text-muted-foreground">
                  {p.authors} "{p.title}" <span className="italic">{p.journal}</span> ({p.year}).{" "}
                  <a href={`https://doi.org/${p.doi}`} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">doi:{p.doi}</a>
                </li>
              ))}
            </ol>
          </motion.div>

          {/* Talks */}
          <motion.div {...fadeIn(0.25)}>
            <h3 className="text-lg font-medium text-primary mb-6">Talks &amp; Presentations</h3>
            <div className="space-y-2">
              {[
                { year: "2026", type: "Contributed Talk", event: "Charting Cosmic Dawn", location: "Copenhagen, Denmark" },
                { year: "2026", type: "Lightning Talk", event: "YCIU Primordial Black Holes Workshop", location: "New Haven, USA" },
                { year: "2026", type: "Contributed Talk", event: "The First Billion Years: 5 Questions in 5 Days", location: "Aspen, USA" },
                { year: "2026", type: "Invited Talk", event: "CSI: Sesto – Cosmology Scene Investigation in Sesto", location: "Sesto, Italy" },
                { year: "2025", type: "Seminar Talk", event: "Swinburne University of Technology", location: "Melbourne, Australia" },
                { year: "2025", type: "Contributed Talk", event: "Kaba Kada Conference: Exploring the First Billion Years of the Universe", location: "Queensland, Australia" },
                { year: "2025", type: "Contributed Talk", event: "The Inaugural Cosmic Frontier Center Conference", location: "Austin, USA" },
                { year: "2025", type: "Seminar Talk", event: "Leiden University", location: "Leiden, The Netherlands" },
                { year: "2024", type: "Contributed Talk", event: "Santa Cruz Workshop on Galaxy Formation", location: "Santa Cruz, USA" },
                { year: "2024", type: "Seminar Talk", event: "Leiden University", location: "Leiden, The Netherlands" },
                { year: "2024", type: "Contributed Talk", event: "RUBIES team meeting", location: "The Netherlands" },
              ].map((t, i) => (
                <div key={i} className="flex flex-col sm:flex-row sm:gap-8 text-sm">
                  <span className="text-muted-foreground sm:min-w-[48px] shrink-0">{t.year}</span>
                  <span>
                    <span className="text-muted-foreground">{t.type}, </span>
                    <span className="italic">{t.event}</span>
                    <span className="text-muted-foreground">, {t.location}</span>
                  </span>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Observing Programs */}
          <motion.div {...fadeIn(0.3)}>
            <h3 className="text-lg font-medium text-primary mb-6">Observing Programs</h3>
            <div className="space-y-5 text-sm">
              <div>
                <p className="font-medium mb-2">James Webb Space Telescope (JWST)</p>
                <div className="space-y-3">
                  <p className="text-muted-foreground">
                    <a href="https://www.stsci.edu/cgi-bin/get-proposal-info?id=8047&observatory=JWST" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">GO #8047</a>{" "}
                    PIs Wang, Nelson, <strong className="text-foreground">Baggen</strong> et al. — "Extremely massive galaxies in the early universe? Confirming the nature of the most model-breaking object by hunting for stellar absorption features" (20.0 hours)
                  </p>
                  <p className="text-muted-foreground">
                    <a href="https://www.stsci.edu/cgi-bin/get-proposal-info?id=5545&observatory=JWST" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">GO #5545</a>{" "}
                    PIs Barrufet, Arellano Cordova, <strong className="text-foreground">Baggen</strong> et al. — "Dead or alive? Unveiling the nature of massive galaxies in the early Universe" (10.5 hours)
                  </p>
                </div>
              </div>
              <div>
                <p className="font-medium mb-2">Keck Observatory</p>
                <p className="text-muted-foreground">PIs Burke, Runnoe and <strong className="text-foreground">Baggen</strong> — "Keck I LRISp: Coming out of their shells: constraining the geometry of Little Red Dots with spectropolarimetry" (1 night)</p>
              </div>
            </div>
          </motion.div>

          {/* Teaching */}
          <motion.div {...fadeIn(0.35)}>
            <h3 className="text-lg font-medium text-primary mb-6">Teaching &amp; Mentoring</h3>
            <div className="space-y-5 text-sm">
              <div>
                <p className="font-medium mb-3">Yale University</p>
                <div className="space-y-2">
                  {[
                    { year: "2024", course: "ASTR 180: Introduction to Relativity and Black Holes" },
                    { year: "2023", course: "ASTR 160: Frontiers and Controversies in Astrophysics" },
                    { year: "2023", course: "ASTR 130: Origins & Search for Life in the Universe" },
                    { year: "2022", course: "ASTR 160: Frontiers and Controversies in Astrophysics" },
                  ].map((t, i) => (
                    <div key={i} className="flex flex-col sm:flex-row sm:gap-8">
                      <span className="text-muted-foreground sm:min-w-[48px] shrink-0">{t.year}</span>
                      <span><span className="text-muted-foreground">Teaching Assistant, </span>{t.course}</span>
                    </div>
                  ))}
                </div>
              </div>
              <div className="flex flex-col sm:flex-row sm:gap-8">
                <span className="text-muted-foreground sm:min-w-[90px] shrink-0">2015–2021</span>
                <span>Private Tutor — Physics, Mathematics, Chemistry (high school level)</span>
              </div>
            </div>
          </motion.div>

          {/* Service & Outreach */}
          <motion.div {...fadeIn(0.4)}>
            <h3 className="text-lg font-medium text-primary mb-6">Service &amp; Outreach</h3>
            <div className="space-y-2 text-sm">
              {[
                { years: "2023–Present", activity: "Referee", detail: "The Astrophysical Journal" },
                { years: "2024–Present", activity: "Astronomy Student Council (ASC)", detail: "Yale University" },
                { years: "2024", activity: "Astronomy on Tap", detail: "New Haven — public outreach talks for general audiences" },
                { years: "2023–Present", activity: "Leitner Family Planetarium", detail: "New Haven — public outreach talks for school groups and children" },
                { years: "2017–2021", activity: "Tour Guide", detail: "The Old Observatory, Leiden" },
              ].map((s, i) => (
                <div key={i} className="flex flex-col sm:flex-row sm:gap-8">
                  <span className="text-muted-foreground sm:min-w-[120px] shrink-0">{s.years}</span>
                  <span><span className="font-medium">{s.activity}</span><span className="text-muted-foreground"> — {s.detail}</span></span>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Activities */}
          <motion.div {...fadeIn(0.45)}>
            <h3 className="text-lg font-medium text-primary mb-6">Activities &amp; Interests</h3>
            <div className="space-y-2 text-sm">
              <div className="flex flex-col sm:flex-row sm:gap-8">
                <span className="text-muted-foreground sm:min-w-[120px] shrink-0">2023–Present</span>
                <span>Yale Club Tennis Team, Yale University</span>
              </div>
              <div className="flex flex-col sm:flex-row sm:gap-8">
                <span className="text-muted-foreground sm:min-w-[120px] shrink-0">2019–2021</span>
                <span>Committee Member, Student Rowing Association K.S.R.V. Njord, Leiden</span>
              </div>
            </div>
          </motion.div>

        </div>
      </div>
    </section>
  );
}
